### ISSUE TITLE
Color neighboorhoods by 'rides' data

### ISSUE THREAD

**Issue by hotzenklotz** [hotzenklotz/TaxiDataNewYork#3]
Coloring only for inital request aka cached data

**Comment by hotzenklotz** [comment]
@stiXits FYI: I just added the dates sliders from issue #6. As part of it, I created a `TaxiDataStore` stub and connected the change events for the date slider:
https://github.com/hotzenklotz/TaxiDataNewYork/blob/master/client/scripts/stores/taxi_data_store.js#L21

**Comment by stiXits** [comment]
ok, cool
